---
title: "W203 Lab 2"
author: "w203 team 1: Kisha Kim, Patricia Gallagher, Sean Koval, Eric Ellestad"
subtitle: 'w203: Lab 2 Pumpkin and weather impact'

output:
  pdf_document: default
  html_document: default
---

``` {r install missing packages}
#install.packages("moments")
#install.packages("jtools")
```

```{r load packages, message = FALSE}
library(tidyverse)
library(ggplot2) 
library(sandwich)
library(stargazer)
library(lmtest)
library(dplyr)
library(readr)
library(car)
library(moments)
library(jtools)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
#source('./src/load_and_clean.R')
#source('./src/get_robust_se.R')
```

```{r load data} 
d_pumpkin <- read.csv("pumpkin_consol.csv")
colnames(d_pumpkin)
```

```{r conduct EDA in this chunk for LHS pumpkin variables}
summary(d_pumpkin$weight_lbs)
plot1 <- d_pumpkin %>%
  ggplot(aes(x=log(weight_lbs))) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Pumpkin Weight")
print(plot1)

summary(d_pumpkin$est_weight)
plot2 <- d_pumpkin %>%
  ggplot(aes(x=est_weight)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Estimated Weight")
print(plot2)

summary(d_pumpkin$ott)
plot3 <- d_pumpkin %>%
  ggplot(aes(x=ott)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Over the top inches")
print(plot3)


```



```{r conduct EDA in this chunk for TMIN variables}

summary(d_pumpkin$TMIN_AVG)
plot11 <- d_pumpkin %>%
  ggplot(aes(x=TMIN_AVG)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of avg min temperature")
print(plot11)

summary(d_pumpkin$TMIN_STDEV)
plot12 <- d_pumpkin %>%
  ggplot(aes(x=TMIN_STDEV)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of stdev of min temp")
print(plot12)

```

``` {r conduct EDA in this chunk for TMAX variables}

summary(d_pumpkin$TMAX_AVG)
plot13 <- d_pumpkin %>%
  ggplot(aes(x=TMAX_AVG)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of avg max temperature")
print(plot13)

summary(d_pumpkin$TMAX_STDEV)
plot14 <- d_pumpkin %>%
  ggplot(aes(x=TMAX_STDEV)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of stdev max temperature")
print(plot14)

```

``` {r conduct EDA in this chunk for MIN/MAX DIFF variables}

summary(d_pumpkin$TEMP_DIFF_AVG)
plot15 <- d_pumpkin %>%
  ggplot(aes(x=TEMP_DIFF_AVG)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of avg MIN/MAX differential")
print(plot15)

summary(d_pumpkin$TEMP_DIFF_STDEV)
plot16 <- d_pumpkin %>%
  ggplot(aes(x=TEMP_DIFF_STDEV)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of stdev MIN/MAX differential")
print(plot16)

```

``` {r conduct EDA in this chunk for temp range variables}

summary(d_pumpkin$TEMP_ABOVE_MIN)
plot17 <- d_pumpkin %>%
  ggplot(aes(x=TEMP_ABOVE_MIN)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of count of days per year above min temp")
print(plot17)

summary(d_pumpkin$TEMP_BELOW_MAX)
plot18 <- d_pumpkin %>%
  ggplot(aes(x=TEMP_BELOW_MAX)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of count of days per year below max temp")
print(plot18)

```


```{r fit a regression model here}
model1 <- lm(weight_lbs ~ TMIN_AVG+TMAX_AVG+PRCP_AVG , data=d_pumpkin)
model2 <- lm(weight_lbs ~ TMIN_AVG+TMAX_AVG+PRCP_AVG+factor(type) , data=d_pumpkin)
model3 <- lm(log(weight_lbs) ~ TMIN_AVG+TMAX_AVG+PRCP_AVG+factor(type) , data=d_pumpkin, na.action = na.exclude)
model4 <- lm(log(weight_lbs) ~ TMIN_AVG+TMAX_AVG+PRCP_AVG+factor(type)+factor(year)+TMIN_STDEV+TMAX_STDEV+PRCP_STDEV , data=d_pumpkin, na.action = na.exclude)

#require(nlme)
anova(model3, model4, test="F")


#model3 <- lm(weight_lbs ~ PRCP_AVG+TMIN_AVG+TMAX_AVG+factor(year) + factor(type), data=d_pumpkin)
#model4 <- lm(weight_lbs ~ PRCP_AVG+TMIN_AVG+TMAX_AVG+ factor(type), data=d_pumpkin)
#model5 <- lm(log(weight_lbs) ~ PRCP_AVG+TMIN_AVG+TMAX_AVG+factor(year) + factor(type), data=d_pumpkin)

stargazer(
   model1, 
   type = 'text', 
   se = list(get_robust_se(model1))
   )

stargazer(
   model2, 
   type = 'text', 
   se = list(get_robust_se(model2))
   )

stargazer(
   model3, 
   type = 'text', 
   se = list(get_robust_se(model3))
   )

stargazer(
   model4, 
   type = 'text', 
   se = list(get_robust_se(model4))
   )




```

``` {r}
coeftest(model1, vcov=vcovHC(model1))
coeftest(model2, vcov=vcovHC(model2))
coeftest(model3, vcov=vcovHC(model3))
coeftest(model4, vcov=vcovHC(model4))
```


```{r code comparing models}
# model 1 vs model 2
anova(model1, model2, test="F")
#p value is smaller than 0.05, reject the null hypothesis. The full model, model2, is a better fit.
# model 2 vs model 3 - model 2 and 3 were not fitted on the same sized dataset
anova(model3, model4, test="F")
#p value is smaller than 0.05, reject the null hypothesis. The full model, model4, is a better fit.

# Same error as above
# model 1 vs model 3
#anova(model1, model3, test="F")
# There are aliased variables (causing error) meaning they are perfectly linear dependent on others. Need to find what those are

#library(aod)
#wald.test(model1, model2, model3)
#?wald.test

```

```{r code to find those aliased variables}
# looks like the relationship to rain total?
alias(model1)
```

```{r code }
# model 1
model1_preds <- predict(model1)
model1_resids <- resid(model1)
# model 2
model2_preds <- predict(model2)
model2_resids <- resid(model2)
# model 3
model3_preds <- predict(model3)
model3_resids <- resid(model3)
# model 4
model4_preds <- predict(model4)
model4_resids <- resid(model4)

plot1 <- ggplot(data=d_pumpkin, aes(model1_preds, model1_resids)) + geom_point() +
stat_smooth()
print(plot1)

plot2 <- ggplot(data=d_pumpkin, aes(model2_preds, model2_resids)) + geom_point() +
stat_smooth()
print(plot2)


plot3 <- ggplot(data=d_pumpkin, aes(model3_preds, model3_resids)) + geom_point() +
stat_smooth()
print(plot3)

plot4 <- ggplot(data=d_pumpkin, aes(model4_preds, model4_resids)) + geom_point() +
stat_smooth()
print(plot4)
```


```{r code and plots assessing normally distributed errors}
plot(model1$residuals)
plot(model2$residuals)
plot(model3$residuals)
# model 1
hist(residuals(model1))
boxplot(residuals(model1)) 
jarque.test(model1$residuals)
# model 2
hist(residuals(model2))
boxplot(residuals(model2)) 
jarque.test(model2$residuals)
plot(model2)

# model 3
hist(residuals(model3))
boxplot(residuals(model3)) 
jarque.test(model3$residuals)

# model 4
hist(residuals(model4))
boxplot(residuals(model4)) 
jarque.test(model4$residuals)
plot(model4)


#kurtosis(model$residuals)-3

#shapiro.test(model$residuals)
#bptest(log(mtcars$mpg)~mtcars$disp+mtcars$hp+mtcars$wt+mtcars$drat)



```

```{r code plotting residuals}
plot_errors_1 <- d_pumpkin %>% 
  ggplot(aes(x=model1_resids)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Residuals Model1")
print(plot_errors_1)

plot_errors_2 <- d_pumpkin %>% 
  ggplot(aes(x=model2_resids)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Residuals Model2")
print(plot_errors_2)
# TODO: Same error as aboe 'aesthetics must be either length 1 or the same...'
plot_errors_3 <- d_pumpkin %>% 
  ggplot(aes(x=model3_resids)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Residuals Model3")
print(plot_errors_3)

plot_errors_4 <- d_pumpkin %>% 
  ggplot(aes(x=model4_resids)) + 
  geom_histogram(bins=100) + 
  ggtitle("Distribution of Residuals Model4")
print(plot_errors_4)

qqplot_1 <- d_pumpkin %>% 
  ggplot(aes(sample=model1_resids)) + 
  stat_qq() + stat_qq_line() +
  ggtitle("QQPlot of Residuals Model1")
print(qqplot_1)

qqplot_2 <- d_pumpkin %>% 
  ggplot(aes(sample=model2_resids)) + 
  stat_qq() + stat_qq_line() +
  ggtitle("QQPlot of Residuals Model2")
print(qqplot_2)
# TODO: Same error as the above for model 3
qqplot_3 <- d_pumpkin %>% 
  ggplot(aes(sample=model3_resids)) + 
  stat_qq() + stat_qq_line() +
  ggtitle("QQPlot of Residuals Model3")
print(qqplot_3)

qqplot_4 <- d_pumpkin %>% 
  ggplot(aes(sample=model4_resids)) + 
  stat_qq() + stat_qq_line() +
  ggtitle("QQPlot of Residuals Model4")
print(qqplot_4)
```

